use std::fs;
use std::path::Path;

#[test]
fn cargo_toml_is_the_only_tracked_manifest_source() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let cargo_toml = fs::read_to_string(root.join("Cargo.toml")).expect("read Cargo.toml");

    assert!(
        !cargo_toml.starts_with("# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO"),
        "Cargo.toml should be hand-authored in the source tree"
    );
    assert!(
        !root.join("Cargo.toml.orig").exists(),
        "Cargo.toml.orig should not be tracked in the source tree"
    );
}
